### ISSUE TITLE
Broken link with state and local

### ISSUE THREAD

**Issue by JoshSunlight** [sunlightlabs/sfcom-wordpress-theme#16]
Click state and local from here: http://wp.sunlightfoundation.com/policy/

Brings you to here: http://wp.sunlightfoundation.com/policy/documents/state-and-local

**Comment by krusynth** [comment]
The live site's entire policy section is really messed up as well.  It'll take some doing to get this all fixed up.

**Comment by krusynth** [comment]
Cleaned up the policy section a bunch.
