### ISSUE TITLE
Subject matter experts

### ISSUE THREAD

**Issue by JoshSunlight** [sunlightlabs/sfcom-wordpress-theme#17]
Can we remove Richard and add Alex? http://wp.sunlightfoundation.com/press/experts/

**Comment by JoshSunlight** [comment]
And add Emily.

**Comment by krusynth** [comment]
You should have access to edit this page, let me know if you can't for any reason.

**Comment by krusynth** [comment]
Cleaned up this page, but it still needs Alex and Emily's info & photos.

**Comment by krusynth** [comment]
More cleanup, added Alex & Emily.
