### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by JoshSunlight** [sunlightlabs/sfcom-wordpress-theme#18]
Is there anyway to add a photo to the spotlight post? Just trying to think of a way to break all the text you see in that space. Open to ideas. 

http://wp.sunlightfoundation.com/

**Comment by krusynth** [comment]
You could add an image manually into that box, or you could include the post's featured image using the `image_size="full"` flag on the `display-posts` shortcode, like so:

`[display-posts id="93957" include_excerpt="true" ignore_sticky_posts="true" excerpt_more_link="true" excerpt_more="Read The Full Story" image_size="full"]`

I've added a style to keep the image from spilling out of the bounds of this box.
