### ISSUE TITLE
Funding page can't move between years

### ISSUE THREAD

**Issue by JoshSunlight** [sunlightlabs/sfcom-wordpress-theme#19]
Appears we can't click between years on the funding page. 

http://wp.sunlightfoundation.com/about/funding/#2013

**Comment by bitb** [comment]
I get this, too. 
Both Firefox and Chrome, Ubuntu 16.04

**Comment by krusynth** [comment]
Fixed with 8b6a8bd4b14a17ea7c64682de422cee88cd65932
