### ISSUE TITLE
Incorrect guest blog bylines

### ISSUE THREAD

**Issue by gregjd** [sunlightlabs/sfcom-wordpress-theme#29]
It appears to me that the way our guest blog system works is that the "real" author in our system is a Sunlighter (usually Louis or Drew), but then blog posts have some attribute that allows the byline to be overridden. For example, [this post](http://sunlightfoundation.com/blog/2016/09/16/opengov-voices-nashvilles-police-data-reveals-racial-burden/) says "by guest author Michael Zoorob" but shows up in [Drew's list of posts](http://sunlightfoundation.com/blog/author/ddoggett/).

<img width="673" alt="screen shot 2016-10-27 at 11 15 07 pm" src="https://cloud.githubusercontent.com/assets/3474451/19793569/3f589a3a-9c9b-11e6-8c52-87bfcf6f7bd0.png">

<img width="291" alt="screen shot 2016-10-27 at 11 16 05 pm" src="https://cloud.githubusercontent.com/assets/3474451/19793617/60c28a32-9c9b-11e6-82f8-6d605f090e2f.png">

But on the new site, the [post itself](http://wp.sunlightfoundation.com/2016/09/16/opengov-voices-nashvilles-police-data-reveals-racial-burden/) says it was written by Drew, and it shows up on Drew's [list of posts](http://wp.sunlightfoundation.com/author/ddoggett/). The guest author byline is nowhere to be found.

<img width="859" alt="screen shot 2016-10-27 at 11 13 44 pm" src="https://cloud.githubusercontent.com/assets/3474451/19793548/0eb8b9d2-9c9b-11e6-8cae-7837722dc16f.png">

Not good.

In an ideal world, the Sunlighter byline would not show up anywhere public, but as a fallback, at least having something like the current system where the Sunlighter byline is obscured on the blog post page would be much, much better.

What confuses me is that when I look at the post interface on WordPress, I don't see any field that contains the guest author info. Perhaps it's permission-level issue, and it does show up for people like Louis?

Here's where it gets interesting. If you look at [this post](http://wp.sunlightfoundation.com/2016/06/20/opengov-voices-transit-data-a-major-success-story-for-common-data-standards/) on the new site, this is a guest post I wrote in June that says it was authored by Drew.

<img width="858" alt="screen shot 2016-10-27 at 11 23 40 pm" src="https://cloud.githubusercontent.com/assets/3474451/19793822/7db5e53e-9c9c-11e6-9e13-5a9fdeb97d64.png">

That's not too weird, given the above problem... except it actually is supposed to say it was authored by my Sunlight user. [Originally](http://web.archive.org/web/20160621121344/http://sunlightfoundation.com/blog/2016/06/20/opengov-voices-transit-data-a-major-success-story-for-common-data-standards/) it said "by guest author Greg Jordan-Detamore" just like any guest post, but after I started working here, we discussed changing it to my Sunlight user so that it would show up on my user profile's list of posts. Louis made this change on Sept 29. Now it looks [like this](https://sunlightfoundation.com/blog/2016/06/20/opengov-voices-transit-data-a-major-success-story-for-common-data-standards/):

<img width="751" alt="screen shot 2016-10-27 at 11 03 19 pm" src="https://cloud.githubusercontent.com/assets/3474451/19793168/abab6a7a-9c99-11e6-8354-57d29602ca5c.png">

and the post shows up in my [list of posts](https://sunlightfoundation.com/team/gjordandetamore/) (and it doesn't show up in [Drew's](http://sunlightfoundation.com/blog/author/ddoggett/?page=2)):

<img width="292" alt="screen shot 2016-10-27 at 11 00 26 pm" src="https://cloud.githubusercontent.com/assets/3474451/19793117/4a758740-9c99-11e6-9b81-9386432abaa7.png">

But not on the new site! On the new site, it says it was written by Drew and it shows up in his [list of posts](http://wp.sunlightfoundation.com/author/ddoggett/page/2/). It doesn't say it was written by me and doesn't show up in my list of posts. That's very weird. The only possibility I can think of is that our old blog posts were imported prior to Sept 29, and thus the new site won't have any changes that were made to old posts since the import date. I hope that's what's up, because if not, then I'm stumped.

**Comment by krusynth** [comment]
There have been two imports - one about a month ago, and a second one in the last couple of days - so that does explain the change you're seeing.

I have _no_ idea where this "guest post" data is stored, though. I'll have to have a look in the database for what's available; that's not Wordpress-standard.

**Comment by krusynth** [comment]
I think it's in here somewhere:  https://github.com/sunlightlabs/sfcom/blob/901a3a31b44f9be5479e540e8bc87193f86b9d3c/blogplusplus/util.py#L65-L66

**Comment by krusynth** [comment]
Ok, this is from the `co-authors-plus` plugin.  I'll try installing that.
