### ISSUE TITLE
Loop pages need design work

### ISSUE THREAD

**Issue by gregjd** [sunlightlabs/sfcom-wordpress-theme#31]
Here's an example using the criminal justice tag page ([before](https://sunlightfoundation.com/blog/tag/criminal-justice/), [after](http://wp.sunlightfoundation.com/taxonomy/term/criminal-justice/)):

<img width="465" alt="screen shot 2016-10-27 at 11 38 30 pm" src="https://cloud.githubusercontent.com/assets/3474451/19794322/3d27fc16-9c9f-11e6-9c34-8ee39407b971.png">
<img width="832" alt="screen shot 2016-10-27 at 11 37 10 pm" src="https://cloud.githubusercontent.com/assets/3474451/19794321/3b238322-9c9f-11e6-9bc5-6569ff52c5bd.png">

The loop pages could use design improvement. (I know that's broad/vague.) That said, because things basically work fine on the loop pages, this seems low-priority.

I submitted this pull request as a slight improvement: https://github.com/sunlightlabs/sfcom-wordpress-theme/pull/30

**Comment by gregjd** [comment]
If I have a little spare time on Monday (we'll see about that...), I might submit a pull request with a few small changes to make it a little more like the current one

**Comment by krusynth** [comment]
I got rid of the category, search, and tag templates, which means everything will just use the `index.php` template instead.
