### ISSUE TITLE
Open Data Policy Guidelines displays awkwardly.

### ISSUE THREAD

**Issue by SLarrick** [sunlightlabs/sfcom-wordpress-theme#33]
Specifically the table of contents and "download" options are meant to display on the side/as a sidebar, but are now full page width and appear up top.

This is one of our most important pages, so we'll want to think through an aesthetics fix.

**Comment by SLarrick** [comment]
http://wp.sunlightfoundation.com/opendataguidelines/

Looking better today than yesterday--although the side bar is still a bit awkward. Thanks for improvements made so far @krues8dr or @gregjd !

**Comment by krusynth** [comment]
Got this cleaned up a bit more.
