### ISSUE TITLE
Kill Sunlight in the News on press page

### ISSUE THREAD

**Issue by JennTopper** [sunlightlabs/sfcom-wordpress-theme#34]
<img width="1074" alt="screen shot 2016-10-28 at 12 19 16 pm" src="https://cloud.githubusercontent.com/assets/13892719/19813685/d064bb2c-9d08-11e6-81aa-a5b297c88c82.png">

You can kill "Sunlight in the News"
It's an old feature that we never update and were trying to kill long ago.

**Comment by krusynth** [comment]
Great, I've removed this.  You all should be able to edit these as well, through the Pages section of Wordpress.
