### ISSUE TITLE
Drop down on contact page 

### ISSUE THREAD

**Issue by JennTopper** [sunlightlabs/sfcom-wordpress-theme#35]
http://wp.sunlightfoundation.com/contact/

Eliminate everything above getting involved. 
<img width="770" alt="screen shot 2016-10-31 at 4 43 05 pm" src="https://cloud.githubusercontent.com/assets/13892719/19870930/22866e5a-9f89-11e6-85c6-d4da064b4191.png">

**Comment by krusynth** [comment]
Great, I moved this into Contact Form 7 so you should be able to edit these moving forward.  I'm having it send to contact@sunlightfoundation.com – but you can edit that under Mail here: http://wp.sunlightfoundation.com/wp-admin/admin.php?page=wpcf7&post=102092&action=edit
