### ISSUE TITLE
Bitcoin

### ISSUE THREAD

**Issue by JennTopper** [sunlightlabs/sfcom-wordpress-theme#37]
Bitcoin donate link goes nowhere
<img width="598" alt="screen shot 2016-10-31 at 4 45 17 pm" src="https://cloud.githubusercontent.com/assets/13892719/19871006/73f03bcc-9f89-11e6-8161-a0a984252db0.png">

http://wp.sunlightfoundation.com/engage/donate/
http://sunlightfoundation.com/bitcoin/

Can we just delete that section of the donate page since the mission statement is repeated below?

**Comment by krusynth** [comment]
All this is getting redone.  #9
