### ISSUE TITLE
Press page

### ISSUE THREAD

**Issue by JennTopper** [sunlightlabs/sfcom-wordpress-theme#38]
In a normal sized browser window, page layout is janky

http://wp.sunlightfoundation.com/press/

<img width="1096" alt="screen shot 2016-10-31 at 4 47 19 pm" src="https://cloud.githubusercontent.com/assets/13892719/19871092/c5eb7220-9f89-11e6-86b4-456c618d2a07.png">

**Comment by krusynth** [comment]
I fixed this up.  The press pages now use a custom template called `Media Template` with your and Josh's contact info in a Widget on the sidebar, replacing the normal sidebar.  The other pages will need this template and similar cleanup.
