### ISSUE TITLE
Multimedia page

### ISSUE THREAD

**Issue by JennTopper** [sunlightlabs/sfcom-wordpress-theme#39]
http://wp.sunlightfoundation.com/press/multimedia/

Is a disaster :(

Can we just leave links to youtube, insta and flickr but not have the photos themselves or rework in someway? Could also just combine into press page and kill the "multimedia section"

**Comment by krusynth** [comment]
This is an in-progress mess from #15 that I'm currently working on – but yes, I would be totally ok with just killing off all the feeds here since it's probably going to be a mess no matter what.

**Comment by krusynth** [comment]
Ok added a list of social links at the bottom of the press page and killed the multimedia page.  I also cleaned up the template.
