### ISSUE TITLE
Header fonts on blog are sized incorrectly

### ISSUE THREAD

**Issue by ElFunkDoctorMaximum** [sunlightlabs/sfcom-wordpress-theme#42]
Header tags seem to be off on blog posts. [Example](http://wp.sunlightfoundation.com/2016/10/28/capitol-cash-how-state-politicians-fundraise-and-campaign-on-the-clock-2), h1 and h3 tags are the same and look like the headline font, h2 tags is all caps and bigger than headline etc. Additionally, it automatically capitalizes the first letter of each word or the entire word, which isn't ideal.

Using iMac/OSX Yosemite/Chrome

**Comment by krusynth** [comment]
This is all based on the original design settings, which did this.  I'll see if I can clean this up a bit.
