### ISSUE TITLE
Facebook share button doesn't work

### ISSUE THREAD

**Issue by ElFunkDoctorMaximum** [sunlightlabs/sfcom-wordpress-theme#43]
On every page I've tried, the Facebook share button launches a box that quickly disappears. The Twitter share button works correctly. [Example](http://wp.sunlightfoundation.com/blog/)

iMac/OSX Yosemite/both Chrome and Safari

**Comment by krusynth** [comment]
This is a conflict with the Root Relative URLs plugin – I'll disable that plugin once the content is all moved and the new site is live.

**Comment by krusynth** [comment]
Ok, disabled the plugin and this appears to be working maybe?
