### ISSUE TITLE
Byline formatting is incorrect

### ISSUE THREAD

**Issue by ElFunkDoctorMaximum** [sunlightlabs/sfcom-wordpress-theme#44]
When more than one author is present on the blog index page or the individual blog post itself, the second author's name is separated by a line that normally would be the division for the post's topic image (e.g. those little symbols that denote "Policy," the pen, "Investigations," the microscope, etc.) See the incorrect examples on the new website [here](https://cloud.githubusercontent.com/assets/6845606/20148171/70f2aa58-a679-11e6-8568-aad16e187591.png) and [here](https://cloud.githubusercontent.com/assets/6845606/20148187/7f8862f6-a679-11e6-92c7-ccc0d8266356.png), and what it is supposed to look like [here](https://cloud.githubusercontent.com/assets/6845606/20148215/9b82f930-a679-11e6-8264-53e46db50de2.png).

iMac/OSX Yosemite/Chrome

**Comment by krusynth** [comment]
Fixed in e12def8935af68d36efc11ac24a6bb84e90ca444
