### ISSUE TITLE
The <section> tag doesn't work

### ISSUE THREAD

**Issue by ElFunkDoctorMaximum** [sunlightlabs/sfcom-wordpress-theme#48]
Previously we used `<section></section>` to input a dotted line in each post, but the new wordpress site simply omits it. [Example here](https://cloud.githubusercontent.com/assets/6845606/20152050/a368c61e-a68a-11e6-94ca-4df5c29d78c8.png) from [this post](http://wp.sunlightfoundation.com/2016/11/01/in-wichita-creating-an-open-data-practice-that-meets-community-needs/); compared to what it used to look like [here](https://cloud.githubusercontent.com/assets/6845606/20152085/ccf6d64c-a68a-11e6-9824-ef25bdc3752c.png). Perhaps this could be replaced with something similar that already works?

iMac/OSX Yosemite/Chrome

**Comment by krusynth** [comment]
I'd recommend using the HR tag for this instead, since `section` has a particular semantic meaning.  I'll add some styling for it.

**Comment by krusynth** [comment]
Yup, just use the `<hr>` – there's button for it on the visual editor too.  I'm afraid I can't fix the old entries without breaking the site horribly, so they'll just have to live without.
